# Generated by Django 4.0.5 on 2022-06-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0006_auto_20210203_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='freepost',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='freepost',
            name='period',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='freepost',
            name='price',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='freepost',
            name='size',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='freepost',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
