# Generated by Django 4.0.5 on 2022-06-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0007_freepost_address_freepost_period_freepost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freepost',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='freepost',
            name='period',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='freepost',
            name='price',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='freepost',
            name='size',
            field=models.CharField(max_length=200),
        ),
    ]
